services:
  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - gateway

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    restart: unless-stopped
    env_file:
      - ./users/.env
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\" --appendonly yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    container_name: todo_gateway
    env_file:
      - ./gateway/.env
    depends_on:
      - user_api
      - todo_api

  user_api:
    build: ./users
    container_name: todo_user_api
    env_file:
      - ./users/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      user_db:
        condition: service_healthy

  user_db:
    image: postgres:18
    container_name: todo_user_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  todo_api:
    build: ./todos
    container_name: todo_todo_api
    env_file:
      - ./todos/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      todo_db:
        condition: service_healthy
      user_api:
        condition: service_started
  todo_db:
    image: postgres:18
    container_name: todo_todo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  redis_data:
  user_postgres_data:
  todo_postgres_data:
